version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing something"
  pre_build:
    commands:
      - echo "We are in build phase"
  build:
    commands:
      - echo "we are in build block"
  post_build:
    commands:
      - echo "we are in post build phase"
artifacts:
  files:
    - '**/*'
  name: myname
